package dev.black.simplelysoap.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllPropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferAutoGeneratedPropertiesEquals(expected, actual);
        assertTransferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAllUpdatablePropertiesEquals(Transfer expected, Transfer actual) {
        assertTransferUpdatableFieldsEquals(expected, actual);
        assertTransferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferAutoGeneratedPropertiesEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableFieldsEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer relevant properties")
            .satisfies(a -> assertThat(a.getAmountSent()).as("check amountSent").isEqualTo(expected.getAmountSent()))
            .satisfies(a -> assertThat(a.getDateTransaction()).as("check dateTransaction").isEqualTo(expected.getDateTransaction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransferUpdatableRelationshipsEquals(Transfer expected, Transfer actual) {
        assertThat(actual)
            .as("Verify Transfer relationships")
            .satisfies(a -> assertThat(a.getSender()).as("check sender").isEqualTo(expected.getSender()))
            .satisfies(a -> assertThat(a.getReceiver()).as("check receiver").isEqualTo(expected.getReceiver()));
    }
}
